### ISSUE TITLE
[FEAT] Add OpenAI support

### ISSUE THREAD

**Issue by Xander-Rudolph** [Xander-Rudolph/mediakube-redux#11]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Use the following marketplace item by @detectiveCrow
https://github.com/detectiveCrow/ai-review-action
https://github.com/marketplace/actions/openai-pr-review

### Reason for change

Because I need someone other than me to review my code

**Comment by cawcaw253** [comment]
@Xander-Rudolph Is it still not work?
https://github.com/Xander-Rudolph/mediakube-redux/actions/runs/4648507055/jobs/8230489984
